name: Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Mysql Setup
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE godatabase;' -u root -pSripragna$1

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: go test -v ./tests
